"use client";

import { useMockRealtime } from "@/hooks/useMockRealtime";
import { INITIAL_CELLS, SYSTEM_COMPONENTS, INITIAL_ALERTS } from "@/lib/mock-data";
import { formatVoltage, formatCurrentMA, formatPowerMW, formatEnergyWh } from "@/lib/utils";

import MetricCard             from "@/components/dashboard/MetricCard";
import RealtimeChart          from "@/components/dashboard/RealtimeChart";
import MeasurementTable       from "@/components/dashboard/MeasurementTable";
import MSTRCellCard           from "@/components/dashboard/MSTRCellCard";
import SystemStatus           from "@/components/dashboard/SystemStatus";
import AlertPanel             from "@/components/dashboard/AlertPanel";
import EnergyProductionChart  from "@/components/dashboard/EnergyProductionChart";

import { Zap, Activity, BatteryCharging, FlameKindling } from "lucide-react";

// ─── Section wrapper for consistent heading style ─────────────────────────────
function Section({ title, subtitle, children }: {
  title: string;
  subtitle?: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="mb-3">
        <p className="card-title">{title}</p>
        {subtitle && <p className="card-subtitle">{subtitle}</p>}
      </div>
      {children}
    </section>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────
export default function OverviewPage() {
  const { latest, history, isConnected } = useMockRealtime();
  const loading = !latest;

  const voltage  = latest?.voltage  ?? 0;
  const currentA = latest?.current  ?? 0;
  const powerW   = latest?.power    ?? 0;
  const energyWh = latest?.energy   ?? 0;

  const older        = history.length > 10 ? history[history.length - 11] : null;
  const voltageTrend = older ? ((voltage  - older.voltage)  / older.voltage)  * 100 : undefined;
  const currentTrend = older ? ((currentA - older.current)  / older.current)  * 100 : undefined;
  const powerTrend   = older ? ((powerW   - older.power)    / older.power)    * 100 : undefined;

  return (
    <div className="p-6 max-w-screen-xl mx-auto" style={{ display: "flex", flexDirection: "column", gap: 28 }}>

      {/* ── Page Header ── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="page-title">Energy Overview</h1>
          <p className="page-subtitle">
            Monitor electrical output generated by your MSTR system in real time.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          {/* Status pill */}
          <div
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-full"
            style={{
              background: isConnected ? "var(--emerald-50)" : "var(--red-50)",
              border: `1px solid ${isConnected ? "var(--emerald-100)" : "var(--red-100)"}`,
            }}
          >
            <div
              className="w-1.5 h-1.5 rounded-full"
              style={{
                background: isConnected ? "var(--emerald-500)" : "var(--red-500)",
                animation: isConnected ? "live-pulse 1.8s ease-in-out infinite" : "none",
              }}
            />
            <span style={{ fontSize: 12, fontWeight: 500, color: isConnected ? "var(--emerald-700)" : "var(--red-600)" }}>
              {isConnected ? "Device Online" : "Device Offline"}
            </span>
          </div>

          {/* Date */}
          <span className="mono hidden sm:inline" style={{ fontSize: 11, color: "var(--text-muted)" }}>
            {new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" })}
          </span>
        </div>
      </div>

      {/* ── KPI Metrics ── */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <MetricCard
          label="Voltage" value={loading ? "—" : formatVoltage(voltage)} unit="V"
          icon={<Zap size={14} strokeWidth={2.5} />}
          trend={voltageTrend} trendLabel="vs 20 s ago"
          accentColor="blue" loading={loading}
        />
        <MetricCard
          label="Current" value={loading ? "—" : formatCurrentMA(currentA)} unit="mA"
          icon={<Activity size={14} strokeWidth={2.5} />}
          trend={currentTrend} trendLabel="vs 20 s ago"
          accentColor="emerald" loading={loading}
        />
        <MetricCard
          label="Power" value={loading ? "—" : formatPowerMW(powerW)} unit="mW"
          icon={<BatteryCharging size={14} strokeWidth={2.5} />}
          trend={powerTrend} trendLabel="V × I"
          accentColor="violet" loading={loading}
        />
        <MetricCard
          label="Energy Generated" value={loading ? "—" : formatEnergyWh(energyWh)} unit="Wh"
          icon={<FlameKindling size={14} strokeWidth={2.5} />}
          trendLabel="Today's accumulated"
          accentColor="amber" loading={loading}
        />
      </div>

      {/* ── Real-Time Chart ── */}
      <RealtimeChart history={history} loading={loading} />

      {/* ── Energy Production ── */}
      <EnergyProductionChart />

      {/* ── Measurement Table ── */}
      <MeasurementTable data={history} loading={loading} />

      {/* ── MSTR Cells ── */}
      <Section title="MSTR Cell Monitoring" subtitle="Individual cell output and health status">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {INITIAL_CELLS.map((cell) => (
            <MSTRCellCard key={cell.id} cell={cell} />
          ))}
        </div>
      </Section>

      {/* ── Status + Alerts ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <SystemStatus components={SYSTEM_COMPONENTS} />
        <AlertPanel   alerts={INITIAL_ALERTS} />
      </div>

    </div>
  );
}
